name: Java CI

on:
  push:
  pull_request:
     branches:
      - develop

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Test
      run: npm test

    - name: Build
      run: npm run build

    # Upload backend artifact on push
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'push'
      with:
        name: Frontend-Package
        path: frontend/build

  Build-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          build-root-directory: backend
          arguments: build
        
      # Upload backend artifact on push
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: Backend-Package
          path: backend/build/libs
